### ISSUE TITLE
Fails to compile on Node 0.10.5 / Ubuntu 10.04

### ISSUE THREAD

**Issue by Rantanen** [TooTallNate/node-vorbis#7]
```
wace@borogove:~/projects/mumble-web$ npm install vorbis
npm http GET https://registry.npmjs.org/vorbis
npm http 304 https://registry.npmjs.org/vorbis
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/bindings

> vorbis@0.1.0 install /home/wace/projects/mumble-web/node_modules/vorbis
> node-gyp rebuild

Generating build/./deps/libvorbis/libvorbis.target.mk
Generating build/./deps/libvorbis/vorbisfile.target.mk
Generating build/./deps/libvorbis/vorbisenc.target.mk
Generating build/./deps/libvorbis/test.target.mk
Generating build/./vorbis.target.mk
Generating build/./deps/libvorbis/libvorbis.Makefile
Generating build/./binding.Makefile
make: Entering directory `/home/wace/projects/mumble-web/node_modules/vorbis/build'
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/mdct.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/smallft.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/block.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/envelope.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/window.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/lsp.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/lpc.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/analysis.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/synthesis.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/psy.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/info.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/floor1.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/floor0.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/res0.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/mapping0.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/registry.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/codebook.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/sharedbook.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/lookup.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/bitrate.o
  AR(target) Release/obj.target/deps/libvorbis/vorbis.a
  CC(target) Release/obj.target/vorbisenc/deps/libvorbis/lib/vorbisenc.o
  AR(target) Release/obj.target/deps/libvorbis/libvorbisenc.a
  CXX(target) Release/obj.target/vorbis/src/binding.o
  SOLINK(target) Release/obj.target/vorbis.node
g++: /home/wace/projects/mumble-web/node_modules/ogg/build/Release/ogg.node: No such file or directory

libogg0 is installed and libogg.a is located at /usr/lib so the -logg dependency on libvorbis shouldn't cause the problem.
wace@borogove:~/projects/mumble-web$ npm install vorbis
npm http GET https://registry.npmjs.org/vorbis
npm http 304 https://registry.npmjs.org/vorbis
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/bindings

> vorbis@0.1.0 install /home/wace/projects/mumble-web/node_modules/vorbis
> node-gyp rebuild

Generating build/./deps/libvorbis/libvorbis.target.mk
Generating build/./deps/libvorbis/vorbisfile.target.mk
Generating build/./deps/libvorbis/vorbisenc.target.mk
Generating build/./deps/libvorbis/test.target.mk
Generating build/./vorbis.target.mk
Generating build/./deps/libvorbis/libvorbis.Makefile
Generating build/./binding.Makefile
make: Entering directory `/home/wace/projects/mumble-web/node_modules/vorbis/build'
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/mdct.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/smallft.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/block.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/envelope.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/window.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/lsp.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/lpc.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/analysis.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/synthesis.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/psy.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/info.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/floor1.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/floor0.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/res0.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/mapping0.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/registry.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/codebook.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/sharedbook.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/lookup.o
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/bitrate.o
  AR(target) Release/obj.target/deps/libvorbis/vorbis.a
  CC(target) Release/obj.target/vorbisenc/deps/libvorbis/lib/vorbisenc.o
  AR(target) Release/obj.target/deps/libvorbis/libvorbisenc.a
  CXX(target) Release/obj.target/vorbis/src/binding.o
  SOLINK(target) Release/obj.target/vorbis.node
g++: /home/wace/projects/mumble-web/node_modules/ogg/build/Release/ogg.node: No such file or directory
```

libogg0 is installed and libogg.a is located at /usr/lib so the -logg dependency on libvorbis shouldn't cause the problem.

Normal ./configure && make for libvorbis compiles just fine too

**Comment by t128** [comment]
just the same issue with:

```
$ node -v
v0.10.25

$ node-gyp -v
v0.10.10
```

**Comment by yura415** [comment]
Also fails to compile with node v4.2.2 on OS X v10.11.
Here is the install log:
```
MacBook-Pro-Georgy:synth Georgy$ npm i --save TooTallNate/node-vorbis

> ogg@1.2.1 install /Users/Georgy/synth/node_modules/ogg
> node-gyp rebuild

2015-11-06 01:56:40.465 xcodebuild[36922:479773] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CC(target) Release/obj.target/libogg/deps/libogg/src/framing.o
  CC(target) Release/obj.target/libogg/deps/libogg/src/bitwise.o
  LIBTOOL-STATIC Release/ogg.a
  CXX(target) Release/obj.target/ogg/src/binding.o
In file included from ../src/binding.cc:23:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace
      'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/Georgy/.node-gyp/4.2.2/include/node/node_buffer.h:31:40: note: candidate
      function not viable: no known conversion from 'uint32_t'
      (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/Georgy/.node-gyp/4.2.2/include/node/node_buffer.h:43:40: note: candidate
      function not viable: 2nd argument ('const char *') would lose const
      qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/Georgy/.node-gyp/4.2.2/include/node/node_buffer.h:28:40: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/Georgy/.node-gyp/4.2.2/include/node/node_buffer.h:36:40: note: candidate
      function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/binding.cc:23:
../node_modules/nan/nan.h:676:12: error: no viable conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Georgy/.node-gyp/4.2.2/include/node/v8.h:210:7: note: candidate
      constructor (the implicit copy constructor) not viable: no known
      conversion from 'v8::MaybeLocal<v8::Object>' to 'const
      v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/Georgy/.node-gyp/4.2.2/include/node/v8.h:210:7: note: candidate
      constructor (the implicit move constructor) not viable: no known
      conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&'
      for 1st argument
class Local {
      ^
/Users/Georgy/.node-gyp/4.2.2/include/node/v8.h:214:13: note: candidate template
      ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/Georgy/.node-gyp/4.2.2/include/node/v8.h:326:13: note: candidate template
      ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/binding.cc:23:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace
      'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../src/binding.cc:27:
../src/node_pointer.h:24:10: error: no matching function for call to
      'NanNewBufferHandle'
  return NanNewBufferHandle((char *)ptr, length, wrap_pointer_cb, user_data);
         ^~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:658:36: note: candidate function not viable: no known
      conversion from 'void (char *, void *)' to 'int' for 3rd argument
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                   ^
../node_modules/nan/nan.h:668:36: note: candidate function not viable: requires
      2 arguments, but 4 were provided
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (
                                   ^
../node_modules/nan/nan.h:675:36: note: candidate function not viable: requires
      single argument 'size', but 4 arguments were provided
  NAN_INLINE v8::Local<v8::Object> NanNewBufferHandle (uint32_t size) {
                                   ^
In file included from ../src/binding.cc:22:
In file included from /Users/Georgy/.node-gyp/4.2.2/include/node/node.h:42:
/Users/Georgy/.node-gyp/4.2.2/include/node/v8.h:221:5: error: assigning to
      'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/Georgy/.node-gyp/4.2.2/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/binding.cc:22:
In file included from /Users/Georgy/.node-gyp/4.2.2/include/node/node.h:42:
/Users/Georgy/.node-gyp/4.2.2/include/node/v8.h:221:5: error: assigning to
      'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/Georgy/.node-gyp/4.2.2/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/binding.cc:22:
In file included from /Users/Georgy/.node-gyp/4.2.2/include/node/node.h:42:
/Users/Georgy/.node-gyp/4.2.2/include/node/v8.h:221:5: error: assigning to
      'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/Georgy/.node-gyp/4.2.2/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/binding.cc:22:
In file included from /Users/Georgy/.node-gyp/4.2.2/include/node/node.h:42:
/Users/Georgy/.node-gyp/4.2.2/include/node/v8.h:221:5: error: assigning to
      'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/Georgy/.node-gyp/4.2.2/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
10 errors generated.
make: *** [Release/obj.target/ogg/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Georgy/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/Georgy/.nvm/versions/node/v4.2.2/bin/node" "/Users/Georgy/.nvm/versions/node/v4.2.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Georgy/synth/node_modules/ogg
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
synth@1.0.0 /Users/Georgy/synth
└── (empty)

npm WARN EPACKAGEJSON synth@1.0.0 No repository field.
npm ERR! Darwin 15.0.0
npm ERR! argv "/Users/Georgy/.nvm/versions/node/v4.2.2/bin/node" "/Users/Georgy/.nvm/versions/node/v4.2.2/bin/npm" "i" "--save" "TooTallNate/node-vorbis"
npm ERR! node v4.2.2
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE

npm ERR! ogg@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ogg@1.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ogg package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ogg
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Georgy/synth/npm-debug.log
npm ERR! code 1
```

**Comment by KingJam** [comment]
I have the same issues on OS X. Any chance of this getting fixed?

**Comment by GeoffreyPlitt** [comment]
Anybody found ogg/vorbis streaming that works?

**Comment by LinusU** [comment]
@GeoffreyPlitt could you try with #20 applied?

```js
npm install TooTallNate/node-vorbis#modernize
```

**Comment by GeoffreyPlitt** [comment]
I moved on to use something else, but if it helps, I tried installing this one and got:
```
 yarn add TooTallNate/node-vorbis#modernize
 ---> Running in 6dbf11e3c1ab
yarn add v0.24.6
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /node_modules/vorbis: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /node_modules/vorbis
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.1.3 | linux | arm
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/node_modules/vorbis/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/node_modules/vorbis/common.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/8.1.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.1.3',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.1.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/node_modules/vorbis',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/node_modules/vorbis/build'
  CC(target) Release/obj.target/libvorbis/deps/libvorbis/lib/mdct.o
In file included from ../deps/libvorbis/lib/mdct.c:46:0:
../deps/libvorbis/lib/os.h:21:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
deps/libvorbis/libvorbis.target.mk:123: recipe for target 'Release/obj.target/libvorbis/deps/libvorbis/lib/mdct.o' failed
make: Leaving directory '/node_modules/vorbis/build'
make: *** [Release/obj.target/libvorbis/deps/libvorbis/lib/mdct.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.14.34+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/vorbis
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
The command '/bin/sh -c yarn add TooTallNate/node-vorbis#modernize' returned a non-zero code: 1
```

**Comment by LinusU** [comment]
Hmm, that's interesting, which platform are you on? Seems like we only have a `config.h` for macOS 32/64-bits and Linux 64-bits.

**Comment by GeoffreyPlitt** [comment]
Oh of course, I should have mentioned. I'm compiling it on RaspberryPiZero/Raspian:
```$ uname -a
Linux raspberrypi 4.14.34+ #1110 Mon Apr 16 14:51:42 BST 2018 armv6l GNU/Linux
```

**Comment by LinusU** [comment]
Opened #21 for ARM support
