### ISSUE TITLE
"undefined is not a function" when running decoder example

### ISSUE THREAD

**Issue by rfwatson** [TooTallNate/node-vorbis#4]
Firstly, thanks for your work on this library.

I'm running into this issue both in my own code, and also when I run the decoder example "out-of-the-box" on node 0.9.11.

```
/xyz/streamcoder/node_modules/ogg/lib/decoder-stream.js:151
    fn(null, packet);
    ^
TypeError: undefined is not a function
    at DecoderStream.onpacket (/xyz/streamcoder/node_modules/ogg/lib/decoder-stream.js:151:5)
    at DecoderStream.g (events.js:192:14)
```

It looks like the stream _read method has been extended to expect a second argument, a function, but it is still being called with a single argument from somewhere, which is causing it to crash.

I couldn't get it working with 0.8.21 either (the same problem if I remember correctly).

Any idea what I could do to fix this?
